spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restro?createDatabaseIfNotExist=true
    username: root
    password: root
  liquibase:
    change-log: classpath*:/db/change-log.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailsenderforjava@gmail.com
    password: iltifceckjkwsohf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

user:
  verify:
    directory:
