spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restro?createDatabaseIfNotExist=true
    username: root
    password: root
  liquibase:
    change-log: classpath*:/db/change-log.xml
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailsenderforjava@gmail.com
    password: iltifceckjkwsohf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

user:
  verify:
    directory:

restro:
  picture:
    upload:
      directory:
